import { Link } from '@tanstack/react-router';
import { useState } from 'react';
import { ArrowUpRight, Bell, ChartNoAxesCombined, ChevronRight, Copy, ExternalLink, Grid2X2, CalendarDays, Store, ShoppingBag, Users, Settings, Zap, Plus, Menu, X, ChevronsUpDown } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { toast } from 'sonner';
import type { ReactNode } from 'react';
export const navigation = [
 {to:'/', label:'Genel Bakış', icon:Grid2X2}, {to:'/magazam', label:'Mağazam', icon:Store}, {to:'/siparisler', label:'Siparişler', icon:ShoppingBag}, {to:'/randevular', label:'Randevular', icon:CalendarDays}, {to:'/musteriler', label:'Müşteriler', icon:Users}, {to:'/analitik', label:'Analitik', icon:ChartNoAxesCombined}, {to:'/ayarlar', label:'Ayarlar', icon:Settings},
] as const;
export function copyLink() { navigator.clipboard.writeText('https://sety.store/emirhan').then(()=>toast.success('Mağaza linki kopyalandı')).catch(()=>toast.error('Link kopyalanamadı')); }
export function Shell({active,children,onAdd}:{active:string;children:ReactNode;onAdd?:()=>void}) {
 const [open,setOpen]=useState(false);
 return <div className="sety-shell"><aside className={`sidebar ${open?'open':''}`}><div className="brand"><span className="brand-mark"><Zap size={23} fill="currentColor"/></span><span>sety</span><span className="beta">BETA</span></div><div className="store-link"><span className="live-dot"/><span>sety.store/emirhan</span><Button variant="ghost" size="icon" className="h-5 w-5" title="Mağaza linkini kopyala" onClick={copyLink}><Copy size={13}/></Button></div><nav className="nav"><div className="nav-label">Çalışma alanı</div>{navigation.map(n=><Link key={n.to} to={n.to} onClick={()=>setOpen(false)} className={`nav-item ${active===n.label?'active':''}`}><n.icon/><span>{n.label}</span>{n.label==='Siparişler'&&<span className="nav-count">3</span>}</Link>)}</nav><div className="sidebar-bottom"><div className="plan"><div className="plan-title"><span>Founder Planı</span><span className="text-primary">9 / 14 gün</span></div><div className="plan-track"><span/></div><p>Hayallerin için daha fazla alan.<br/>Satışlarından komisyon alınmaz.</p><Link to="/ayarlar">Planı keşfet <ArrowUpRight size={12}/></Link></div><div className="account"><div className="avatar">EA</div><div><strong>Emirhan Arslan</strong><p>emirhan@sety.store</p></div><Button variant="ghost" size="icon" className="ml-auto h-7 w-7" title="Hesap ayarları" asChild><Link to="/ayarlar"><ChevronsUpDown size={14}/></Link></Button></div></div></aside><main className="main"><header className="topbar"><div className="flex items-center gap-3"><Button className="menu-mobile" variant="ghost" size="icon" onClick={()=>setOpen(!open)} aria-label="Menüyü aç">{open?<X/>:<Menu/>}</Button><div className="breadcrumb">Panel <ChevronRight size={12}/><span>{active}</span></div></div><div className="top-actions"><Button variant="ghost" size="icon" className="notification text-muted-foreground" title="Bildirimler" onClick={()=>toast('Yeni bildiriminiz bulunmuyor')}><Bell size={18}/></Button><span className="h-5 border-l border-border"/><Button variant="outline" className="view-store text-xs" asChild><Link to="/magazam"><ExternalLink/>Mağazayı Gör</Link></Button><Button onClick={onAdd} className="text-xs"><Plus/>Ürün Ekle</Button></div></header><div className="content">{children}<footer className="footer-note"><span>© 2026 Sety · Üret, paylaş, kazan.</span><span className="flex items-center gap-2"><span className="live-dot"/>Tüm sistemler çalışıyor <span className="ml-2">· Örnek veriler</span></span></footer></div></main></div>;
}
